name: app_invv1
description: Application de gestion d'inventaire
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # flutter_localizations:
  #   sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_messaging: ^16.0.3
  firebase_storage: ^13.0.3
  syncfusion_flutter_datagrid: ^29.2.11
  syncfusion_flutter_xlsio: ^29.2.11
  fl_chart: ^1.1.0
  provider: ^6.1.2
  path_provider: ^2.1.1
  intl: ^0.20.2
  excel: ^4.0.6
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.2.2
  js: ^0.7.2
  http: ^1.2.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true 